import raw from "./geolibre-catalog.json";
import type { ExperienceLevel } from "../policy/types";

export type Tier = "basic" | "intermediate" | "advanced";

export interface CatalogItem {
  id: string;
  label: string;
  tier: Tier;
}

export interface DataSourceItem extends CatalogItem {
  section: string;
}

export interface MenuItem extends CatalogItem {
  menuId: string;
}

export interface Catalog {
  source: { repository: string; commit: string };
  dataSourceSections: { id: string; label: string }[];
  dataSources: DataSourceItem[];
  menus: CatalogItem[];
  menuItems: MenuItem[];
  plugins: CatalogItem[];
}

/** GeoLibre's hideable ids, generated by `npm run sync:catalog`. */
export const catalog: Catalog = {
  ...raw,
  dataSources: raw.dataSources as DataSourceItem[],
  menus: raw.menus as CatalogItem[],
  menuItems: raw.menuItems as MenuItem[],
  plugins: raw.plugins.map((plugin) => ({
    id: plugin.id,
    label: plugin.name,
    tier: plugin.tier as Tier,
  })),
};

const TIER_RANK: Record<Tier, number> = { basic: 0, intermediate: 1, advanced: 2 };
const LEVEL_RANK: Record<ExperienceLevel, number> = { beginner: 0, intermediate: 1, advanced: 2 };

/**
 * Whether an experience level shows an item of the given tier, matching
 * GeoLibre's `levelAllowsTier`.
 *
 * @param level - The experience level.
 * @param tier - The item's complexity tier.
 * @returns True when the item is visible at that level.
 */
export function levelAllowsTier(level: ExperienceLevel, tier: Tier): boolean {
  return TIER_RANK[tier] <= LEVEL_RANK[level];
}

export interface HiddenSets {
  hiddenDataSources: string[];
  hiddenPlugins: string[];
  hiddenMenus: string[];
  hiddenMenuItems: string[];
}

/**
 * The hidden id lists GeoLibre derives from an experience-level preset,
 * matching its `presetHiddenSets` for the built-in plugins.
 *
 * @param level - The experience level.
 * @returns The ids each list hides at that level.
 */
export function presetHiddenSets(level: ExperienceLevel): HiddenSets {
  const hidden = (items: CatalogItem[]) =>
    items.filter((item) => !levelAllowsTier(level, item.tier)).map((item) => item.id);
  return {
    hiddenDataSources: hidden(catalog.dataSources),
    hiddenPlugins: hidden(catalog.plugins),
    hiddenMenus: hidden(catalog.menus),
    hiddenMenuItems: hidden(catalog.menuItems),
  };
}
