import type {
  DeploymentPolicy,
  InterfacePolicy,
  OperatorSettings,
  ServiceEntry,
} from "./types";

/** Where the generated files are mounted in the GeoLibre container. */
export const ADMIN_PROFILE_MOUNT = "/usr/share/nginx/html/admin-profile.json";
export const SERVICES_MOUNT = "/config/geolibre-services.json";

function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null || value === "") return true;
  if (Array.isArray(value)) return false;
  if (typeof value === "object") return Object.values(value).every(isEmpty);
  return false;
}

/**
 * Drop unset values and empty sections so the exported document only states
 * what differs from GeoLibre's defaults. Empty arrays are kept: an empty
 * `capabilities` list is meaningful (grant nothing).
 *
 * @param policy - The policy being edited.
 * @returns A minimal equivalent policy.
 */
export function cleanPolicy(policy: DeploymentPolicy): DeploymentPolicy {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(policy)) {
    if (value === undefined) continue;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      const section = Object.fromEntries(
        Object.entries(value).filter(([, inner]) => inner !== undefined && inner !== ""),
      );
      if (!isEmpty(section)) out[key] = section;
    } else {
      out[key] = value;
    }
  }
  return out as unknown as DeploymentPolicy;
}

/**
 * The `admin-profile.json` GeoLibre reads today, or null when the policy
 * leaves the interface alone.
 *
 * @param policy - The deployment policy.
 * @returns The admin profile object, or null.
 */
export function toAdminProfile(policy: DeploymentPolicy): InterfacePolicy | null {
  const profile = cleanPolicy({ version: 1, interface: policy.interface }).interface;
  return profile ?? null;
}

/**
 * The `GEOLIBRE_SERVICES_FILE` document, or null without a catalog.
 *
 * @param policy - The deployment policy.
 * @returns `{ services: [...] }`, or null.
 */
export function toServicesFile(policy: DeploymentPolicy): { services: ServiceEntry[] } | null {
  const services = policy.services?.catalog ?? [];
  if (services.length === 0) return null;
  return {
    services: services.map((service) => ({
      id: service.id.trim(),
      name: service.name.trim(),
      kind: service.kind,
      ...(service.category ? { category: service.category } : {}),
      fields: service.fields,
    })),
  };
}

export interface Setting {
  name: string;
  value: string;
  note?: string;
}

/**
 * Container environment variables for `docker run -e` / Compose.
 *
 * @param policy - The deployment policy.
 * @param operator - Env-only server settings.
 * @returns Runtime environment variables in a stable order.
 */
export function runtimeEnv(policy: DeploymentPolicy, operator: OperatorSettings): Setting[] {
  const env: Setting[] = [];
  const add = (name: string, value: string | undefined, note?: string) => {
    if (value !== undefined && value.trim() !== "") env.push({ name, value: value.trim(), note });
  };
  add("GEOLIBRE_SHARE_URL", policy.sharing?.shareUrl);
  add("GEOLIBRE_COLLAB_URL", policy.sharing?.collabUrl);
  add("GEOLIBRE_EMBED_ORIGINS", policy.sharing?.embedOrigins?.join(","));
  add("GEOLIBRE_GEOLENS_URL", policy.geolens?.url);
  add("GEOLIBRE_APP_NAME", policy.branding?.appName);
  if (toServicesFile(policy)) add("GEOLIBRE_SERVICES_FILE", SERVICES_MOUNT, "mount geolibre-services.json here");
  if (policy.services?.builtins === false) add("GEOLIBRE_BUILTIN_SERVICES", "off");
  if (!operator.sidecar) add("GEOLIBRE_DISABLE_SIDECAR", "1");
  if (operator.sidecar) {
    add("GEOLIBRE_CONVERSION_ROOTS", operator.conversionRoots);
    add("GEOLIBRE_POSTGIS_HOSTS", operator.postgisHosts);
  }
  return env;
}

/**
 * Settings GeoLibre only reads at build time (`docker build --build-arg`).
 *
 * @param policy - The deployment policy.
 * @returns Build arguments in a stable order.
 */
export function buildArgs(policy: DeploymentPolicy): Setting[] {
  const args: Setting[] = [];
  if (policy.capabilities) {
    args.push({
      name: "VITE_GEOLIBRE_CAPABILITIES",
      value: policy.capabilities.length ? policy.capabilities.join(",") : "none",
    });
  }
  if (policy.branding?.welcome === false) args.push({ name: "VITE_WELCOME_DISABLED", value: "1" });
  return args;
}

function shellQuote(value: string): string {
  return /^[A-Za-z0-9_./:,=@+-]+$/.test(value) ? value : `'${value.replace(/'/g, `'\\''`)}'`;
}

function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

/**
 * A `.env` file for `docker run --env-file` or Compose's `env_file`.
 *
 * @param env - Runtime variables from {@link runtimeEnv}.
 * @returns The file content.
 */
export function toEnvFile(env: Setting[]): string {
  const lines = ["# Generated by geolibre-admin. Runtime settings for the GeoLibre container."];
  for (const item of env) {
    if (item.note) lines.push(`# ${item.note}`);
    lines.push(`${item.name}=${item.value}`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Shell commands that build (when needed) and run the configured image.
 *
 * @param policy - The deployment policy.
 * @param operator - Env-only server settings.
 * @returns A copy-pasteable shell snippet.
 */
export function toDockerCommands(policy: DeploymentPolicy, operator: OperatorSettings): string {
  const args = buildArgs(policy);
  const env = runtimeEnv(policy, operator);
  const image = args.length ? "geolibre-custom" : "ghcr.io/opengeos/geolibre:latest";
  const blocks: string[] = [];
  if (args.length) {
    const lines = ["# Build-time settings: run from a GeoLibre checkout.", "docker build \\"];
    for (const arg of args) lines.push(`  --build-arg ${arg.name}=${shellQuote(arg.value)} \\`);
    lines.push(`  -t ${image} .`);
    blocks.push(lines.join("\n"));
  }
  const run = ["docker run -d --name geolibre -p 8080:80 \\"];
  for (const item of env) run.push(`  -e ${item.name}=${shellQuote(item.value)} \\`);
  if (toAdminProfile(policy)) run.push(`  -v "$PWD/admin-profile.json:${ADMIN_PROFILE_MOUNT}:ro" \\`);
  if (toServicesFile(policy)) run.push(`  -v "$PWD/geolibre-services.json:${SERVICES_MOUNT}:ro" \\`);
  run.push(`  ${image}`);
  blocks.push(run.join("\n"));
  return `${blocks.join("\n\n")}\n`;
}

/**
 * A Docker Compose service definition for the configured deployment.
 *
 * @param policy - The deployment policy.
 * @param operator - Env-only server settings.
 * @returns A `compose.yaml` document.
 */
export function toCompose(policy: DeploymentPolicy, operator: OperatorSettings): string {
  const args = buildArgs(policy);
  const env = runtimeEnv(policy, operator);
  const lines = ["services:", "  geolibre:"];
  if (args.length) {
    lines.push("    build:", "      context: ./GeoLibre  # a GeoLibre checkout", "      args:");
    for (const arg of args) lines.push(`        ${arg.name}: ${yamlQuote(arg.value)}`);
  } else {
    lines.push("    image: ghcr.io/opengeos/geolibre:latest");
  }
  lines.push('    ports:', '      - "8080:80"');
  if (env.length) {
    lines.push("    environment:");
    for (const item of env) lines.push(`      ${item.name}: ${yamlQuote(item.value)}`);
  }
  const volumes: string[] = [];
  if (toAdminProfile(policy)) volumes.push(`      - ./admin-profile.json:${ADMIN_PROFILE_MOUNT}:ro`);
  if (toServicesFile(policy)) volumes.push(`      - ./geolibre-services.json:${SERVICES_MOUNT}:ro`);
  if (volumes.length) lines.push("    volumes:", ...volumes);
  return `${lines.join("\n")}\n`;
}

export interface ExportFile {
  name: string;
  description: string;
  content: string;
}

/**
 * Every artifact the editor can download for a policy.
 *
 * @param policy - The deployment policy.
 * @param operator - Env-only server settings.
 * @returns Files in display order; optional ones are omitted when unused.
 */
export function exportFiles(policy: DeploymentPolicy, operator: OperatorSettings): ExportFile[] {
  const files: ExportFile[] = [
    {
      name: "deployment.json",
      description: "The whole policy as one versioned document (draft schema).",
      content: `${JSON.stringify(cleanPolicy(policy), null, 2)}\n`,
    },
  ];
  const profile = toAdminProfile(policy);
  if (profile) {
    files.push({
      name: "admin-profile.json",
      description: "Interface profile: serve it from the app root (web) or the app config directory (desktop).",
      content: `${JSON.stringify(profile, null, 2)}\n`,
    });
  }
  const services = toServicesFile(policy);
  if (services) {
    files.push({
      name: "geolibre-services.json",
      description: `Curated service library: mount it and point GEOLIBRE_SERVICES_FILE at it.`,
      content: `${JSON.stringify(services, null, 2)}\n`,
    });
  }
  files.push(
    {
      name: "geolibre.env",
      description: "Runtime environment for docker run --env-file or Compose.",
      content: toEnvFile(runtimeEnv(policy, operator)),
    },
    {
      name: "docker-run.sh",
      description: "Build (only when build-time settings are used) and run commands.",
      content: toDockerCommands(policy, operator),
    },
    {
      name: "compose.yaml",
      description: "A Docker Compose service using the files above.",
      content: toCompose(policy, operator),
    },
  );
  return files;
}
