/**
 * Write `schema/deployment.schema.json` and the precompiled validator.
 *
 * The validator is generated with Ajv's standalone mode so the app never
 * compiles a schema at runtime (which needs `new Function` and would break
 * under a strict Content-Security-Policy).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { deploymentSchema } from "../src/policy/schema";

const here = import.meta.dirname;
const schemaPath = resolve(here, "../schema/deployment.schema.json");
writeFileSync(schemaPath, `${JSON.stringify(deploymentSchema, null, 2)}\n`);

const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  allowUnionTypes: true,
  code: { source: true, esm: true },
});
const validate = ajv.compile(deploymentSchema);
const banner = "// Generated by `npm run sync:schema` from src/policy/schema.ts. Do not edit.\n";
const validatorPath = resolve(here, "../src/policy/schema-validator.generated.js");
// Ajv's ESM output still pulls its runtime helpers in with require(); hoist
// them into default imports so the module is plain ESM for Vite and Node.
const runtimeImports: string[] = [];
// CommonJS interop differs between bundlers and Node (the default import is
// either `module.exports` or `exports.default`), so accept both shapes.
const code = standaloneCode(ajv, validate).replace(
  /require\("([^"]+)"\)(\.default)?/g,
  (_, path: string, viaDefault: string | undefined) => {
    const name = `ajvRuntime${runtimeImports.length}`;
    runtimeImports.push(`import ${name} from "${path}.js";`);
    return viaDefault ? `(${name}.default ?? ${name})` : name;
  },
);
writeFileSync(validatorPath, `${banner}${runtimeImports.join("\n")}\n${code}`);

console.log(`Wrote ${schemaPath} and ${validatorPath}`);
